sylius_grid:
    grids:
        nextstore_sylius_gift_card_admin_gift_card:
            driver:
                name: doctrine/orm
                options:
                    class: "%nextstore_sylius_gift_card.model.gift_card.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                createdAt: desc
            limits: [100, 250, 500, 1000]
            fields:
                customer:
                    type: twig
                    label: sylius.ui.customer
                    options:
                        template: "@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Grid/Field/customer.html.twig"
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                amount:
                    type: twig
                    label: nextstore_sylius_gift_card.ui.amount
                    path: .
                    sortable: amount
                    options:
                        template: "@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Grid/Field/amount.html.twig"
                channel:
                    type: twig
                    label: sylius.ui.channel
                    sortable: channel.code
                    options:
                        template: "@SyliusAdmin/Order/Grid/Field/channel.html.twig"
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                createdAt:
                    type: datetime
                    label: sylius.ui.created
                    sortable: ~
                    options:
                        format: d-m-Y
                boughtAtOrder:
                    type: twig
                    label: nextstore_sylius_gift_card.ui.bought_at_order
                    path: orderItemUnit
                    sortable: orderItemUnit.orderItem.order.number
                    options:
                        template: "@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Grid/Field/item_units_order.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code]
                channel:
                    type: entity
                    label: sylius.ui.channel
                    form_options:
                        class: "%sylius.model.channel.class%"
                amount:
                    type: money
                    label: sylius.ui.amount
                    options:
                        currency_field: currencyCode
                customerEmail:
                    type: string
                    label: nextstore_sylius_gift_card.ui.customer_email
                    options:
                        fields: [customer.email]
                boughtAtOrder:
                    type: string
                    label: nextstore_sylius_gift_card.ui.bought_at_order
                    options:
                        fields: [orderItemUnit.orderItem.order.number]
                enabled:
                    label: sylius.ui.enabled
                    type: boolean
            actions:
                main:
                    configuration:
                        type: default
                        label: nextstore_sylius_gift_card.ui.configuration
                        icon: cog
                        options:
                            link:
                                route: nextstore_sylius_gift_card_admin_gift_card_configuration_index
                    balance:
                        type: gift_card_balance
                    create:
                        type: gift_card_create
                item:
                    list_orders:
                        type: gift_card_list_conditional
                        label: nextstore_sylius_gift_card.ui.list_orders
                        options:
                            visible: resource.hasAppliedCompletedOrders
                            link:
                                route: nextstore_sylius_gift_card_admin_gift_card_orders_index
                                parameters:
                                    id: resource.id
                    download_pdf:
                        type: show
                        label: nextstore_sylius_gift_card.ui.download_pdf
                        options:
                            link:
                                route: nextstore_sylius_gift_card_admin_gift_card_pdf
                                parameters:
                                    id: resource.id
                    resend_email:
                        type: gift_card_resend_email
                        label: nextstore_sylius_gift_card.ui.resend_email
                        options:
                            visible: resource.hasOrderOrCustomer
                            link:
                                route: nextstore_sylius_gift_card_admin_gift_card_resend_email
                                parameters:
                                    id: resource.id
                    update:
                        type: update
                    delete:
                        type: gift_card_delete_conditional
                        options:
                            visible: resource.isDeletable
