sylius_grid:
    grids:
        nextstore_sylius_gift_card_admin_gift_card_order:
            extends: sylius_admin_order
            driver:
                options:
                    repository:
                        method: createCompletedQueryBuilderByGiftCard
                        arguments:
                            giftCard: $id
            fields:
                coveredByGiftCards:
                    type: twig
                    label: nextstore_sylius_gift_card.ui.covered_by_gift_cards
                    path: .
                    options:
                        template: "@NextstoreSyliusGiftCardPlugin/Admin/Order/Grid/Field/coveredByGiftCards.html.twig"
