imports:
    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/grids/nextstore_sylius_gift_card_admin_gift_card.yaml" }
    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/grids/nextstore_sylius_gift_card_admin_gift_card_configuration.yaml" }
    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/grids/nextstore_sylius_gift_card_admin_gift_card_order.yaml" }
    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/grids/nextstore_sylius_gift_card_shop_gift_card.yaml" }

sylius_grid:
    templates:
        action:
            gift_card_create: "@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/create.html.twig"
            gift_card_delete_conditional: "@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/delete_conditional.html.twig"
            gift_card_balance: "@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/gift_card_balance.html.twig"
            gift_card_list_conditional: "@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/list_conditional.html.twig"
            gift_card_resend_email: '@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/resend_email.html.twig'
