nextstore_sylius_gift_card_shop:
    resource: "@NextstoreSyliusGiftCardPlugin/src/Resources/config/routes/shop.yaml"

nextstore_sylius_gift_card_admin:
    resource: "@NextstoreSyliusGiftCardPlugin/src/Resources/config/routes/admin.yaml"
    prefix: /admin

nextstore_sylius_gift_card_admin_ajax:
    resource: "@NextstoreSyliusGiftCardPlugin/src/Resources/config/routes/admin_ajax.yaml"
    prefix: /admin/ajax
    
nextstore_sylius_gift_card_admin_api:
    resource: "@NextstoreSyliusGiftCardPlugin/src/Resources/config/routes/admin_api.yaml"
    prefix: /api/v{version}
