winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                nextstore_decrement_gift_card_amount:
                    on: ["create"]
                    do: ["@nextstore_sylius_gift_card.modifier.order_gift_card_amount", "decrement"]
                    args: ["object"]
                nextstore_increment_gift_card_amount:
                    on: ["cancel"]
                    do: ["@nextstore_sylius_gift_card.modifier.order_gift_card_amount", "increment"]
                    args: ["object"]
                nextstore_order_cancellation_gift_card:
                    on: ["cancel"]
                    do: ["@nextstore_sylius_gift_card.operator.order_gift_card", "disable"]
                    args: ["object"]
