winzou_state_machine:
    sylius_order_payment:
        callbacks:
            after:
                nextstore_gift_card_enable:
                    on: ["pay"]
                    do: ["@nextstore_sylius_gift_card.operator.order_gift_card", "enable"]
                    args: ["object"]
                nextstore_gift_card_send:
                    on: ["pay"]
                    do: ["@nextstore_sylius_gift_card.operator.order_gift_card", "send"]
                    args: ["object"]
