imports:
    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/grids.yaml" }
    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/sylius_ui.yaml" }

    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order.yaml" }
    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order_checkout.yaml" }
    - { resource: "@NextstoreSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order_payment.yaml" }

sylius_mailer:
    emails:
        gift_card_customer:
            subject: nextstore_sylius_gift_card.email.new_gift_card
            template: "@NextstoreSyliusGiftCardPlugin/Email/giftCardToCustomer.html.twig"
        gift_card_order:
            subject: nextstore_sylius_gift_card.email.your_gift_cards_you_bought_in_the_order
            template: "@NextstoreSyliusGiftCardPlugin/Email/giftCardsFromOrder.html.twig"
        gift_card_receiver:
            subject: nextstore_sylius_gift_card.email.your_gift_cards_you_bought_in_the_order
            template: "@NextstoreSyliusGiftCardPlugin/Email/giftCardsFromOrderToReceiver.html.twig"

jms_serializer:
    metadata:
        directories:
            nextstore-sylius-gift-card-sylius:
                namespace_prefix: "Nextstore\\SyliusGiftCardPlugin\\Model"
                path: "@NextstoreSyliusGiftCardPlugin/Resources/config/serializer"

liip_imagine:
    filter_sets:
        nextstore_sylius_gift_card_background:
            filters:
                thumbnail: { size: [1200], mode: inset }

sylius_ui:
    events:
        nextstore_sylius_gift_card.admin.gift_card_configuration.create.javascripts:
            blocks:
                preview_uploaded_image: '@NextstoreSyliusGiftCardPlugin/Admin/GiftCardConfiguration/_javascripts.html.twig'

        nextstore_sylius_gift_card.admin.gift_card_configuration.update.javascripts:
            blocks:
                preview_uploaded_image: '@NextstoreSyliusGiftCardPlugin/Admin/GiftCardConfiguration/_javascripts.html.twig'
                live_pdf_rendering_js: '@NextstoreSyliusGiftCardPlugin/Admin/GiftCardConfiguration/Update/_javascripts.html.twig'
        
        nextstore_sylius_gift_card.admin.gift_card.create.javascripts:
            blocks:
                send_customer_email_js: '@NextstoreSyliusGiftCardPlugin/Admin/GiftCard/Create/_javascripts.html.twig'
        
        nextstore_sylius_gift_card.shop.account.gift_card.index.after_content_header:
            blocks:
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: nextstore_sylius_gift_card.shop.account.gift_card.index.after_content_header
        
        nextstore_sylius_gift_card.shop.account.gift_card.index.after_grid:
            blocks:
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: nextstore_sylius_gift_card.shop.account.gift_card.index.after_grid
        
        nextstore_sylius_gift_card.shop.account.gift_card.index.header:
            blocks:
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: nextstore_sylius_gift_card.shop.account.gift_card.index.header
        
        nextstore_sylius_gift_card.shop.cart.summary.applied_gift_cards:
            blocks:
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: nextstore_sylius_gift_card.shop.cart.summary.applied_gift_cards
